"""Compatibility facade for the split spine proofreading interface.

The implementation is divided between :mod:`proofreading_functions` and
:mod:`proofreading_ui`, but this module remains the stable import target for
existing notebooks and callers.
"""

if __package__:
    from .proofreading_functions import (
        ALL_ANSWER_KEYS,
        ANALYSIS_FIELDS,
        DesignState,
        ISSUE_FIELDS,
        NEURON_ID,
        SPINE_TYPES,
        TOTAL_SECTIONS,
        TOTAL_SPINES,
        SECTION_CSV_FIELDS,
        SPINE_CSV_FIELDS,
        SUBSECTION_CSV_FIELDS,
        VALID_STRUCTURE_FIELD,
        derive_spine_validity,
        get_neuron_id_from_mesh_path,
        get_validation_csv_path,
        read_validation_csv,
        restore_validation_state,
        save_validation_state,
        section_summary_row,
        section_summary_rows,
        snapshot_validation_state,
        write_validation_csv,
        _build_mock_sections,
        _build_section_subsections,
        _empty_subsection,
        _format_spine_type,
        _load_real_sections,
        _make_section,
    )
    from .proofreading_ui import (
        FONT_DIRECTORY,
        PROJECTION_CELLS,
        SCALE_BAR_UNIT_LABEL,
        SCALE_BAR_WORLD_UNITS_PER_DISPLAY_UNIT,
        SpineValidationDesign,
        _build_css,
        _font_face_css,
        _scale_bar_js,
        build_preview,
        build_sample_viewport,
        display_preview,
    )
else:  # Support notebooks that add ``lib`` directly to ``sys.path``.
    from proofreading_functions import (
        ALL_ANSWER_KEYS,
        ANALYSIS_FIELDS,
        DesignState,
        ISSUE_FIELDS,
        NEURON_ID,
        SPINE_TYPES,
        TOTAL_SECTIONS,
        TOTAL_SPINES,
        SECTION_CSV_FIELDS,
        SPINE_CSV_FIELDS,
        SUBSECTION_CSV_FIELDS,
        VALID_STRUCTURE_FIELD,
        derive_spine_validity,
        get_neuron_id_from_mesh_path,
        get_validation_csv_path,
        read_validation_csv,
        restore_validation_state,
        save_validation_state,
        section_summary_row,
        section_summary_rows,
        snapshot_validation_state,
        write_validation_csv,
        _build_mock_sections,
        _build_section_subsections,
        _empty_subsection,
        _format_spine_type,
        _load_real_sections,
        _make_section,
    )
    from proofreading_ui import (
        FONT_DIRECTORY,
        PROJECTION_CELLS,
        SCALE_BAR_UNIT_LABEL,
        SCALE_BAR_WORLD_UNITS_PER_DISPLAY_UNIT,
        SpineValidationDesign,
        _build_css,
        _font_face_css,
        _scale_bar_js,
        build_preview,
        build_sample_viewport,
        display_preview,
    )


__all__ = [
    'ANALYSIS_FIELDS',
    'ISSUE_FIELDS',
    'VALID_STRUCTURE_FIELD',
    'SECTION_CSV_FIELDS',
    'SPINE_CSV_FIELDS',
    'SUBSECTION_CSV_FIELDS',
    'derive_spine_validity',
    'get_neuron_id_from_mesh_path',
    'get_validation_csv_path',
    'read_validation_csv',
    'restore_validation_state',
    'save_validation_state',
    'section_summary_row',
    'section_summary_rows',
    'snapshot_validation_state',
    'write_validation_csv',
    'ALL_ANSWER_KEYS',
    'SPINE_TYPES',
    'TOTAL_SECTIONS',
    'TOTAL_SPINES',
    'NEURON_ID',
    'FONT_DIRECTORY',
    'PROJECTION_CELLS',
    'SCALE_BAR_UNIT_LABEL',
    'SCALE_BAR_WORLD_UNITS_PER_DISPLAY_UNIT',
    'DesignState',
    'SpineValidationDesign',
    'build_sample_viewport',
    'build_preview',
    'display_preview',
    '_font_face_css',
    '_build_css',
    '_scale_bar_js',
    '_make_section',
    '_build_mock_sections',
    '_format_spine_type',
    '_build_section_subsections',
    '_empty_subsection',
    '_load_real_sections',
]
